FROM docker.elastic.co/logstash/logstash:8.4.2
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
ADD pipeline/ /usr/share/logstash/pipeline/
ADD config/ /usr/share/logstash/config/
COPY ./logstash.yml /usr/share/logstash/config/logstash.yml
